name: AutoresizingScrollViewExample
options:
  bundleIdPrefix: com.autoresizingscrollview
packages:
  AutoresizingScrollView:
    url: https://github.com/RomanPodymov/AutoresizingScrollView
    from: 1.0.1
targets:
  ForiOS:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
    dependencies:
      - package: AutoresizingScrollView
  FortvOS:
    type: application
    platform: tvOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
    dependencies:
      - package: AutoresizingScrollView
  FormacOS:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources: [Sources, macOS]
    info:
      path: Info.plist
    dependencies:
      - package: AutoresizingScrollView
